<?php
require dirname(__DIR__).'/backend/app/bootstrap.php';$user=require_permission('view_staff');$error='';
try{[$where,$params,$filters]=staff_filter($_GET);}catch(InvalidArgumentException $e){$error=$e->getMessage();[$where,$params,$filters]=staff_filter([]);}
// These dates refer to history events, not employment start dates.
$filterSource=$filters;unset($filterSource['from'],$filterSource['to']);[$where,$params]=staff_filter($filterSource);
foreach(['from'=>'>=','to'=>'<='] as $key=>$op)if($filters[$key]!==''){$where.=($where?' AND ':' WHERE ').'h.effective_date'.$op.'?';$params[]=$filters[$key];}
$join=' FROM staff_history h JOIN staff_directory s ON s.id=h.staff_id JOIN users u ON u.id=h.actor_id';
$total=(int)query('SELECT COUNT(*)'.$join.$where,$params)->fetchColumn();$page=page_number($total);
$rows=query('SELECT h.*,s.full_name,s.employee_code,u.full_name actor_name'.$join.$where.' ORDER BY h.effective_date DESC,h.id DESC LIMIT 25 OFFSET '.(($page-1)*25),$params)->fetchAll();
page_start('Staff history',$user);?><div class="section-head"><div><h2>A shared record of every change</h2><p class="muted">Manual entries, effective dates, and the TL who recorded them. Department filters use current assignments.</p></div><?php if(user_can('export_staff')):?><a class="button button-secondary" href="export.php?<?=e(http_build_query(array_merge($filters,['type'=>'history'])))?>">Export history</a><?php endif;?></div><?php error_notice($error);?><section class="panel"><form method="get" class="filter-grid"><label>Employee search<input name="q" value="<?=e($filters['q'])?>" placeholder="Name, code or position"></label><label>Current department<select name="department_id"><option value="">All departments</option><?php options(active_departments(),$filters['department_id']);?></select></label><label>Effective from<input type="date" name="from" value="<?=e($filters['from'])?>"></label><label>Effective to<input type="date" name="to" value="<?=e($filters['to'])?>"></label><div class="actions"><button class="button">Apply</button><a class="button button-secondary" href="history.php">Reset</a></div></form></section><section class="panel"><?php foreach($rows as $entry):?><article class="timeline-item"><h3><a href="employee.php?id=<?=$entry['staff_id']?>"><?=e($entry['full_name'])?></a> · <?=e(ucfirst($entry['event_type']))?></h3><small>Effective <?=e($entry['effective_date'])?> · <?=e($entry['actor_name'])?> · Recorded <?=e($entry['created_at'])?></small><p><?=e($entry['notes'])?></p><?php if($changes=history_changes($entry)):?><details><summary>View changes</summary><ul class="changes"><?php foreach($changes as $change):?><li><?=e($change)?></li><?php endforeach;?></ul></details><?php endif;?></article><?php endforeach;if(!$rows):?><p class="empty">No history matches these filters.</p><?php endif;pagination($total,$page);?></section><?php page_end();
