<?php
require __DIR__.'/app/bootstrap.php';$user=require_permission('create_tickets');$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();try{
        $subject=input('subject',255);$issue=input('issue',20000);$category=input('category',80);$priority=input('priority',20);$department=positive_id($_POST,'department_id');$assignee=positive_id($_POST,'assignee_id');$staffId=positive_id($_POST,'staff_id');
        if($subject==='' || $issue==='')throw new InvalidArgumentException('Subject and issue details are required.');
        if(!isset(TICKET_CATEGORIES[$category]) || !isset(TICKET_PRIORITIES[$priority]))throw new InvalidArgumentException('Select a valid category and priority.');
        if(!in_array($department,array_map('intval',array_column(active_departments(),'id')),true))throw new InvalidArgumentException('Select a department.');
        if($assignee && !in_array($assignee,array_map('intval',array_column(active_users(),'id')),true))throw new InvalidArgumentException('Select an active assignee.');
        $employee=$staffId?query('SELECT full_name FROM staff_directory WHERE id=?',[$staffId])->fetchColumn():false;
        if(!$employee)throw new InvalidArgumentException('Select an employee.');
        $uploads=ticket_uploads();
        db()->beginTransaction();
        query('INSERT INTO tickets(ticket_number,issue_escalator,subject,category,department_id,employee_name,description,issue,priority,assignee_id,created_by,staff_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',['WTS-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3))),$user['full_name'],$subject,$category,$department,$employee,$issue,$issue,$priority,$assignee?:null,$user['id'],$staffId]);
        $id=(int)db()->lastInsertId();if($assignee)sync_ticket_assignees($id,[$assignee]);sync_ticket_departments($id,[$department]);activity($id,(int)$user['id'],'created',['subject'=>$subject,'priority'=>$priority]);save_ticket_uploads($id,(int)$user['id'],$uploads);db()->commit();flash('Ticket created.');redirect('ticket.php?id='.$id);
    }catch(InvalidArgumentException $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}
}
$v=fn($key,$default='')=>$_SERVER['REQUEST_METHOD']==='POST'?request_string($_POST,$key):$default;
page_start('Create ticket',$user);?><a class="back-link" href="index.php">&larr; Tickets</a><section class="panel"><h2>What needs attention?</h2><p class="muted">Link a request to an employee and give it a clear owner.</p><?php error_notice($error);?><form method="post" enctype="multipart/form-data"><?php csrf_field();?><div class="form-grid"><label class="wide">Subject *<input name="subject" maxlength="255" required value="<?=e($v('subject'))?>"></label><label>Employee *<select name="staff_id" required><option value="">Select employee</option><?php options(query("SELECT id,CONCAT(full_name,'  ·  ',employee_code) name FROM staff_directory ORDER BY full_name")->fetchAll(),$v('staff_id',request_string($_GET,'staff_id')));?></select></label><label>Department *<select name="department_id" required><option value="">Select department</option><?php options(active_departments(),$v('department_id'));?></select></label><label>Category *<select name="category" required><?php enum_options(array_combine(array_keys(TICKET_CATEGORIES),array_keys(TICKET_CATEGORIES)),$v('category'));?></select></label><label>Priority *<select name="priority" required><?php enum_options(TICKET_PRIORITIES,$v('priority','normal'));?></select></label><label class="wide">Assigned to<select name="assignee_id"><option value="">Unassigned</option><?php options(active_users(),$v('assignee_id'),'full_name');?></select></label><label class="wide">Issue details *<textarea name="issue" rows="7" maxlength="20000" required><?=e($v('issue'))?></textarea></label><label class="wide">Attachments (optional)<input type="file" name="attachments[]" multiple accept=".pdf,.txt,.csv,.jpg,.jpeg,.png,.webp,.docx,.xlsx"><small>Up to 3 files, 2 MB each. PDF, text, CSV, images, DOCX or XLSX. Select files again if validation fails.</small></label></div><div class="form-footer"><button class="button">Create ticket</button><a class="button button-secondary" href="index.php">Cancel</a></div></form></section><?php page_end();
