<?php
function icon(string $name): string {
    $paths=['dashboard'=>'M4 4h6v6H4z M14 4h6v10h-6z M4 14h6v6H4z M14 18h6v2h-6z','tickets'=>'M5 4h14v16H5z M8 8h8 M8 12h8 M8 16h5','staff'=>'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M2 21v-3a6 6 0 0 1 12 0v3 M17 4a4 4 0 0 1 0 8 M18 15a5 5 0 0 1 4 5','history'=>'M3 11a9 9 0 1 1 2 7 M3 4v7h7 M12 7v6l4 2','reports'=>'M4 20V10h4v10 M10 20V4h4v16 M16 20v-7h4v7','team'=>'M3 21V7h8v14 M11 21V3h10v18 M6 11h2 M6 15h2 M15 7h2 M15 11h2 M15 15h2'];
    return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'.($paths[$name]??$paths['staff']).'"/></svg>';
}
function page_start(string $title, ?array $user=null): void {
    $user??=current_user();$page=basename($_SERVER['PHP_SELF']);
    $nav=[['dashboard.php','Overview','dashboard','view_all_tickets'],['index.php','Tickets','tickets','view_all_tickets'],['staff.php','Staff directory','staff','view_staff'],['history.php','Staff history','history','view_staff'],['departments.php','Departments & teams','team','view_staff'],['reports.php','Reports & exports','reports','view_reports'],['users.php','Accounts & TLs','staff','manage_users']];
    ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> · Wheettle</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="assets/css/app.css"><link rel="stylesheet" href="assets/css/wheettle.css"><link rel="stylesheet" href="assets/css/layout-fixes.css"></head><body class="wts">
    <a class="skip-link" href="#main-content">Skip to main content</a><aside class="topbar"><a class="brand" href="dashboard.php"><img class="strata-logo" src="assets/stratastaff-logo.png" alt="Strata Staff Global"><span class="workspace-brand">Wheettle<span>PEOPLE & SERVICE</span></span></a><nav class="nav" aria-label="Primary"><p class="nav-label">Workspace</p><?php foreach($nav as [$href,$label,$glyph,$permission]):if(!user_can($permission))continue;$active=$page===$href || ($href==='staff.php' && in_array($page,['employee.php','employee-form.php'])) || ($href==='index.php' && in_array($page,['ticket.php','create-ticket.php']));?><a class="nav-link <?=$active?'active':''?>" href="<?=$href?>" <?=$active?'aria-current="page"':''?>><?=icon($glyph)?><span><?=$label?></span></a><?php endforeach;?></nav><div class="sidebar-bottom"><span class="muted">A record of every chapter.</span><a href="change-password.php">Account settings</a><a href="logout.php">Sign out</a></div></aside>
    <header class="app-header"><div><p class="eyebrow">Wheettle workspace</p><h1><?=e($title)?></h1></div><div class="app-header-actions"><span class="header-date"><?=date('D, M j, Y')?></span><div class="account-chip"><span class="employee-avatar"><?=e(mb_substr($user['full_name'],0,1))?></span><span><strong><?=e($user['full_name'])?></strong><small><?=e($user['role_name'])?></small></span></div></div></header><main id="main-content" class="page"><div class="content-shell"><?php if(!empty($_SESSION['flash'])):?><div class="notice" role="status"><?=e($_SESSION['flash'])?></div><?php unset($_SESSION['flash']);endif;
}
function page_end(): void { echo '</div><footer class="wts-footer">Wheettle · Strata Staff Global</footer></main></body></html>'; }
function error_notice(string $error): void { if($error!=='')echo '<div class="error" role="alert">'.e($error).'</div>'; }
